export const tagList =[
    { label: 'Fruit', value: 'Fruit' },
    { label: 'Vegetable', value: 'Vegetable' },
    { label: 'Other', value: 'Other' },
    { label: 'Apple', value: 'Apple' },
    { label: 'Orange', value: 'Orange' },
    { label: 'Lemon', value: 'Lemon' },
    { label: 'Feijoa', value: 'Feijoa' },
    { label: 'Lettuce', value: 'Lettuce' },
    { label: 'Tomato', value: 'Tomato' },
    { label: 'Expires Soon', value: 'Expires Soon' },
    { label: 'Tree', value: 'Tree' },
    { label: 'Fresh', value: 'Fresh' },
    { label: 'Garden', value: 'Garden' },
];